apiVersion: v1
kind: Pod
metadata:
  name: private-reg
  labels:
    app: my-app
    namespace: my-app-ns
spec:
  containers:
    - name: private-reg-container
      image: practicek8s.jfrog.io/docker-practice-docker-local/openmrs:1.0
  imagePullSecrets:
    - name: artregcred2
