apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  imagePullSecrets:
    - name: artregcred
  containers:
    - name: private-reg-container
      image: practicek8s.jfrog.io/docker-practice-docker-local/openmrs:1.0
      ports:
        - containerPort:8080
      
