---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: daemonset-test
  labels:
    app: fluentd
spec:
  minReadySeconds: 3
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
        purpose: logcollection
    spec:
      containers:
        - name: fluentd
          image: fluentd:lateset
          port:
            - containerPort: 24224 