---
apiVersion: v1
kind: Pod
metadata:
  name: initcontianers-test
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins:lts-jdk11
      ports:
        - containerPort: 8080
  initContainers:
    - name: init-app-service
      image: alpine:3
      cmd: ["sleep", "10s"]
  initContainers:
    - name: init-db-service
      image: alpine:3
      cmd: ["sleep", "10s"]